services:
  database:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: receiplan
      MYSQL_USER: receiplan
      MYSQL_PASSWORD: receiplan_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: receiplan
      PMA_PASSWORD: receiplan_pwd
    ports:
      - "8081:80"

volumes:
  database_data:
